method: random
metric:
  goal: maximize
  name: max_exact_match
parameters:
  batch_size:
    value: 8
  count_of_epoch:
    value: 30
  criterion:
    value: CrossEntropyLoss
  hidden_dropout_prob:
    values:
    - 0.1
    - 0.2
    - 0.4
  attention_probs_dropout_prob:
    values:
    - 0.1
    - 0.2
    - 0.4
  summary_last_dropout:
    values:
    - 0.0
    - 0.1
    - 0.3
  lr:
    max: 3.0e-04
    min: 1.0e-08
    distribution: log_uniform
  max_length:
    values:
    - 512
    - 386
    - 256
  model_name:
    value: 'deberta'
  optimizer:
    value: 'adamW'
  scheduler:
    value: 'linear'
  warmup_ratio:
    values:
    - 0.0
    - 0.10
    - 0.25
  stride:
    values:
    - 128
    - 186
  weight_decay:
    values:
    - 0.0
    - 0.01
    - 0.001
    - 0.0001
