method: random
metric:
  goal: maximize
  name: max_exact_match
parameters:
  batch_size:
    value: 2
  count_of_epoch:
    value: 4
  criterion:
    value: CrossEntropyLoss
  hidden_dropout_prob:
    values:
    - 0.1
    - 0.2
  attention_probs_dropout_prob:
    values:
    - 0.1
    - 0.2
  summary_last_dropout:
    values:
    - 0.0
    - 0.1
    - 0.3
  lr:
    values:
    - 0.0003
    - 0.0001
    - 0.00002
    - 0.000005
    - 0.000001
    - 0.000003
    - 0.0000005 
    - 0.0000001
  max_length:
    values:
    - 512
    - 386
    - 256
  model_name:
    value: 'deberta'
  optimizer:
    value: 'adamW'
  scheduler:
    value: 'linear'
  warmup_ratio:
    values:
    - 0.0
    - 0.10
    - 0.25
  stride:
    values:
    - 128
    - 186
  weight_decay:
    values:
    - 0.0
    - 0.01
    - 0.0001
