method: random
metric:
  goal: maximize
  name: eval/max_exact_score
parameters:
  batch_size:
    value: 8
  count_of_epoch:
    value: 30
  criterion:
    value: CrossEntropyLoss
  hidden_dropout_prob:
    values:
    - 0.1
    - 0.3
  attention_probs_dropout_prob:
    values:
    - 0.1
    - 0.3
  pooler_dropout:
    values:
    - 0.0
    - 0.2
  lr:
    values:
    - 0.00001
    - 0.000005
    - 0.000001
    - 0.0000005 
    - 0.0000001
  max_length:
    values:
    - 512
    - 386
    - 256
  model_name:
    value: 'mdeberta'
  optimizer:
    value: 'adamW'
  scheduler:
    value: 'linear'
  warmup_ratio:
    values:
    - 0.0
    - 0.10
    - 0.25
  stride:
    values:
    - 128
    - 186
  weight_decay:
    values:
    - 0.0
    - 0.01
    - 0.0001