method: random
metric:
  goal: maximize
  name: test_exact_match
parameters:
  batch_size:
    value: 4
  count_of_epoch:
    values:
    - 10
    - 20
    - 40
  criterion:
    value: CrossEntropyLoss
  dropout:
    values:
    - 0
    - 0.2
    - 0.4
    - 0.6
  lr:
    max: 0.0003
    min: 1.0e-07
  max_length:
    values:
    - 1000
    - 512
    - 256
  model_name:
    values:
    - mobilebert
    - distilbert
    - longformer
  optimizer:
    value:
    - adam
  scheduler:
    value: StepLR
  stride:
    values:
    - 128
    - 186
  weight_decay:
    values:
    - 0
    - 0.01
    - 0.001
    - 0.0001
